<?php

namespace DoctrineProxies\__CG__\com\novaconcept\entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ClientInfo extends \com\novaconcept\entity\ClientInfo implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'com\\novaconcept\\entity\\ClientInfo' . "\0" . 'id', '' . "\0" . 'com\\novaconcept\\entity\\ClientInfo' . "\0" . 'name', '' . "\0" . 'com\\novaconcept\\entity\\ClientInfo' . "\0" . 'description', '' . "\0" . 'com\\novaconcept\\entity\\ClientInfo' . "\0" . 'createdOn', '' . "\0" . 'com\\novaconcept\\entity\\ClientInfo' . "\0" . 'modifiedOn', '' . "\0" . 'com\\novaconcept\\entity\\ClientInfo' . "\0" . 'clientAuthentication', '' . "\0" . 'com\\novaconcept\\entity\\ClientInfo' . "\0" . 'configModule', '' . "\0" . 'com\\novaconcept\\entity\\ClientInfo' . "\0" . 'clientAuthorizationCollection', '' . "\0" . 'com\\novaconcept\\entity\\ClientInfo' . "\0" . 'clientAccountCollection', '' . "\0" . 'com\\novaconcept\\entity\\ClientInfo' . "\0" . 'clientPermissionCollection', '' . "\0" . 'com\\novaconcept\\entity\\ClientInfo' . "\0" . 'accountInfoCollection');
        }

        return array('__isInitialized__', '' . "\0" . 'com\\novaconcept\\entity\\ClientInfo' . "\0" . 'id', '' . "\0" . 'com\\novaconcept\\entity\\ClientInfo' . "\0" . 'name', '' . "\0" . 'com\\novaconcept\\entity\\ClientInfo' . "\0" . 'description', '' . "\0" . 'com\\novaconcept\\entity\\ClientInfo' . "\0" . 'createdOn', '' . "\0" . 'com\\novaconcept\\entity\\ClientInfo' . "\0" . 'modifiedOn', '' . "\0" . 'com\\novaconcept\\entity\\ClientInfo' . "\0" . 'clientAuthentication', '' . "\0" . 'com\\novaconcept\\entity\\ClientInfo' . "\0" . 'configModule', '' . "\0" . 'com\\novaconcept\\entity\\ClientInfo' . "\0" . 'clientAuthorizationCollection', '' . "\0" . 'com\\novaconcept\\entity\\ClientInfo' . "\0" . 'clientAccountCollection', '' . "\0" . 'com\\novaconcept\\entity\\ClientInfo' . "\0" . 'clientPermissionCollection', '' . "\0" . 'com\\novaconcept\\entity\\ClientInfo' . "\0" . 'accountInfoCollection');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ClientInfo $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedOn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedOn', array());

        return parent::getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    public function getModifiedOn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModifiedOn', array());

        return parent::getModifiedOn();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientAuthentication($clientAuthentication)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientAuthentication', array($clientAuthentication));

        return parent::setClientAuthentication($clientAuthentication);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientAuthentication()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientAuthentication', array());

        return parent::getClientAuthentication();
    }

    /**
     * {@inheritDoc}
     */
    public function setConfigModule($configModule)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConfigModule', array($configModule));

        return parent::setConfigModule($configModule);
    }

    /**
     * {@inheritDoc}
     */
    public function getConfigModule()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConfigModule', array());

        return parent::getConfigModule();
    }

    /**
     * {@inheritDoc}
     */
    public function getClientAuthorizationCollection()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientAuthorizationCollection', array());

        return parent::getClientAuthorizationCollection();
    }

    /**
     * {@inheritDoc}
     */
    public function getClientAccountCollection()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientAccountCollection', array());

        return parent::getClientAccountCollection();
    }

    /**
     * {@inheritDoc}
     */
    public function getClientPermissionCollection()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientPermissionCollection', array());

        return parent::getClientPermissionCollection();
    }

    /**
     * {@inheritDoc}
     */
    public function getAccountInfoCollection()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccountInfoCollection', array());

        return parent::getAccountInfoCollection();
    }

    /**
     * {@inheritDoc}
     */
    public function prePersist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'prePersist', array());

        return parent::prePersist();
    }

    /**
     * {@inheritDoc}
     */
    public function modifiedOnPreUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'modifiedOnPreUpdate', array());

        return parent::modifiedOnPreUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function mapPostData($requestData)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'mapPostData', array($requestData));

        return parent::mapPostData($requestData);
    }

    /**
     * {@inheritDoc}
     */
    public function mergePostData($requestData)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'mergePostData', array($requestData));

        return parent::mergePostData($requestData);
    }

    /**
     * {@inheritDoc}
     */
    public function validatePermissions($permissions, $accountId = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'validatePermissions', array($permissions, $accountId));

        return parent::validatePermissions($permissions, $accountId);
    }

    /**
     * {@inheritDoc}
     */
    public function validateAccount($account)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'validateAccount', array($account));

        return parent::validateAccount($account);
    }

    /**
     * {@inheritDoc}
     */
    public function hasPermission($permission, $accountId = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasPermission', array($permission, $accountId));

        return parent::hasPermission($permission, $accountId);
    }

    /**
     * {@inheritDoc}
     */
    public function getData($includes = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData', array($includes));

        return parent::getData($includes);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

}
